import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/widgets/ui.dart';
import '../../data/habit_models.dart';
import '../providers/habit_providers.dart';

class AddHabitScreen extends ConsumerStatefulWidget { const AddHabitScreen({super.key, this.habitId}); final String? habitId; @override ConsumerState<AddHabitScreen> createState() => _AddHabitScreenState(); }
class _AddHabitScreenState extends ConsumerState<AddHabitScreen> {
  late TextEditingController title; late TextEditingController subtitle; String category = 'Health'; String frequency = 'Daily'; String difficulty = 'Hard'; int xp = 50; String icon = '🌱'; Color color = AppColors.green; List<String> reminders = ['7:00 AM']; bool loaded = false;
  @override void initState() { super.initState(); title = TextEditingController(text: 'Morning Meditation'); subtitle = TextEditingController(text: '10 minutes of mindfulness to start the day.'); }
  void _load() { if (loaded) return; loaded = true; final h = _findHabit(widget.habitId); if (h != null) { title.text = h.title; subtitle.text = h.subtitle; category = h.category; frequency = h.frequency; difficulty = h.difficulty; xp = h.xpReward; icon = h.icon; color = h.color; reminders = h.reminderTimes; } }

  Habit? _findHabit(String? id) {
    if (id == null) return null;
    for (final habit in ref.read(habitsControllerProvider)) {
      if (habit.id == id) return habit;
    }
    return null;
  }

  @override Widget build(BuildContext context) { _load(); return AppPage(padding: const EdgeInsets.fromLTRB(24, 46, 24, 120), children: [
    Row(children: [IconButton.filledTonal(onPressed: () => context.go('/home'), icon: const Icon(Icons.close)), Expanded(child: Column(children: [Text(widget.habitId == null ? 'Add New Habit' : 'Edit Habit', style: const TextStyle(fontSize: 26, fontWeight: FontWeight.w900)), const Text('Build a better you, one habit at a time.', style: TextStyle(color: AppColors.muted, fontSize: 17))])), ElevatedButton(onPressed: _save, style: ElevatedButton.styleFrom(backgroundColor: AppColors.green, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 18), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14))), child: const Text('Save', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800)))]),
    const SizedBox(height: 24), Center(child: Stack(children: [Container(width: 116, height: 116, decoration: BoxDecoration(shape: BoxShape.circle, color: color.withOpacity(.12)), child: Center(child: Text(icon, style: const TextStyle(fontSize: 58)))), Positioned(right: 0, bottom: 4, child: SoftCard(padding: const EdgeInsets.all(8), child: const Icon(Icons.edit, size: 18)))])), const SizedBox(height: 24),
    _field(title, true), const SizedBox(height: 12), _field(subtitle, false), const SizedBox(height: 22), _label('Category'), _selector(['💚\nHealth','📖\nLearning','💼\nProductivity','🍃\nWellness','💳\nFinance'], category, (v){setState(() => category = v.split('\n').last);}), const SizedBox(height: 22), _label('Frequency'), _seg(['Daily','Weekly','Monthly','Custom'], frequency, (v)=>setState(()=>frequency=v)), const SizedBox(height: 18),
    SoftCard(child: Row(children: [const Icon(Icons.notifications_none), const SizedBox(width: 10), const Expanded(child: Text('Reminder', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w800))), const Icon(Icons.chevron_right), const SizedBox(width: 8), Pill(child: Text(reminders.first, style: const TextStyle(color: AppColors.green, fontWeight: FontWeight.w800))), TextButton.icon(onPressed: () => setState(() => reminders = [...reminders, '8:30 PM']), icon: const Icon(Icons.add), label: const Text('Add another time'))])), const SizedBox(height: 22),
    _label('Difficulty & XP Reward'), Row(children: [('Easy',10,AppColors.green),('Medium',25,AppColors.blue),('Hard',50,AppColors.orange),('Elite',100,AppColors.purple)].map((d) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 8), child: SoftCard(borderColor: difficulty == d.$1 ? d.$3 : null, color: d.$3.withOpacity(.05), onTap: () => setState(() { difficulty = d.$1; xp = d.$2; }), child: Column(children: [Text('⭐', style: TextStyle(fontSize: 26, color: d.$3)), Text(d.$1, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700)), Text('+${d.$2} XP', style: TextStyle(color: d.$3, fontWeight: FontWeight.w900))]))))).toList()),
    const SizedBox(height: 22), _label('Color & Icon'), Wrap(spacing: 20, children: habitColorOptions.map((c) => InkWell(onTap: () => setState(() => color = c), child: Container(width: 46, height: 46, decoration: BoxDecoration(shape: BoxShape.circle, color: c, border: Border.all(color: color == c ? c.withOpacity(.3) : Colors.transparent, width: 8)))).toList()), const SizedBox(height: 18), Wrap(spacing: 12, runSpacing: 12, children: habitIconOptions.map((e) => InkWell(onTap: () => setState(() => icon = e), child: Container(width: 74, height: 64, decoration: BoxDecoration(borderRadius: BorderRadius.circular(14), color: icon == e ? color.withOpacity(.12) : Colors.transparent, border: Border.all(color: icon == e ? color : AppColors.line)), child: Center(child: Text(e, style: const TextStyle(fontSize: 30))))).toList()), const SizedBox(height: 26),
    const SoftCard(color: Color(0xFFF0F8ED), child: Row(children: [Text('🤖', style: TextStyle(fontSize: 54)), SizedBox(width: 18), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('AI Suggestion ✨', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), Text('People like you also build this habit.', style: TextStyle(color: AppColors.muted)), SizedBox(height: 10), Wrap(spacing: 8, children: [Pill(child: Text('Drink Water', style: TextStyle(color: AppColors.green))), Pill(child: Text('Gratitude Journal', style: TextStyle(color: AppColors.green))), Pill(child: Text('Deep Breathing', style: TextStyle(color: AppColors.green)))])])), Icon(Icons.chevron_right)])),
  ]); }
  Widget _field(TextEditingController c, bool big) => TextField(controller: c, maxLength: big ? null : 100, style: TextStyle(fontSize: big ? 26 : 18, fontWeight: big ? FontWeight.w800 : FontWeight.w500), decoration: InputDecoration(filled: true, fillColor: Colors.white.withOpacity(.4), border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: const BorderSide(color: AppColors.line)), suffixIcon: big ? const Icon(Icons.cancel_outlined) : null));
  Widget _label(String s) => Padding(padding: const EdgeInsets.only(bottom: 10), child: Text(s, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w800)));
  Widget _selector(List<String> items, String selected, void Function(String) onTap) => Row(children: items.map((it) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 8), child: SoftCard(padding: const EdgeInsets.all(12), borderColor: it.endsWith(selected) ? AppColors.green : null, color: it.endsWith(selected) ? AppColors.green.withOpacity(.08) : null, onTap: () => onTap(it), child: Center(child: Text(it, textAlign: TextAlign.center, style: const TextStyle(fontSize: 16))))))).toList());
  Widget _seg(List<String> items, String selected, void Function(String) onTap) => Row(children: items.map((it) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 8), child: OutlinedButton(onPressed: () => onTap(it), style: OutlinedButton.styleFrom(backgroundColor: it == selected ? AppColors.green.withOpacity(.09) : null, side: BorderSide(color: it == selected ? AppColors.green : AppColors.line), padding: const EdgeInsets.symmetric(vertical: 16)), child: Text(it, style: TextStyle(color: it == selected ? AppColors.green : Theme.of(context).colorScheme.onSurface, fontWeight: FontWeight.w800))))).toList());
  Future<void> _save() async { final existing = _findHabit(widget.habitId); if (existing != null) { await ref.read(habitsControllerProvider.notifier).save(existing.copyWith(title: title.text, subtitle: subtitle.text, category: category, icon: icon, colorValue: color.value, frequency: frequency, difficulty: difficulty, xpReward: xp, reminderTimes: reminders)); } else { await ref.read(habitsControllerProvider.notifier).create(title: title.text, subtitle: subtitle.text, category: category, icon: icon, color: color, frequency: frequency, difficulty: difficulty, xpReward: xp, reminders: reminders); } if (mounted) context.go('/home'); }
}
