import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/widgets/ui.dart';
import '../providers/habit_providers.dart';

class CalendarScreen extends ConsumerWidget {
  const CalendarScreen({super.key});
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final month = ref.watch(visibleMonthProvider);
    final selected = ref.watch(selectedDateProvider);
    final habits = ref.watch(habitsControllerProvider);
    final comps = ref.watch(completionsProvider);
    final selectedCount = habits.where((h) => comps.any((c) => c.habitId == h.id && DateUtils.isSameDay(c.date, selected))).length;
    final firstGrid = month.subtract(Duration(days: (DateTime(month.year, month.month, 1).weekday - 1)));
    return AppPage(children: [
      Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Calendar', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900)), const Text('Track your consistency', style: TextStyle(fontSize: 22, color: AppColors.muted))])), OutlinedButton.icon(onPressed: () { ref.read(selectedDateProvider.notifier).state = DateUtils.dateOnly(DateTime.now()); ref.read(visibleMonthProvider.notifier).state = DateTime(DateTime.now().year, DateTime.now().month); }, icon: const Icon(Icons.calendar_today), label: const Text('Today'))]),
      const SizedBox(height: 24), SoftCard(child: Column(children: [Row(children: [IconButton(onPressed: () => ref.read(visibleMonthProvider.notifier).state = DateTime(month.year, month.month - 1), icon: const Icon(Icons.chevron_left, color: AppColors.green, size: 34)), Expanded(child: Center(child: Text(DateFormat('MMMM yyyy').format(month), style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w800)))), IconButton(onPressed: () => ref.read(visibleMonthProvider.notifier).state = DateTime(month.year, month.month + 1), icon: const Icon(Icons.chevron_right, color: AppColors.muted, size: 34))]), const SizedBox(height: 16), Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d) => Text(d, style: const TextStyle(color: AppColors.muted))).toList()), const SizedBox(height: 12), GridView.builder(shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), itemCount: 42, gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 7, mainAxisSpacing: 10, crossAxisSpacing: 10), itemBuilder: (_, i) { final day = firstGrid.add(Duration(days: i)); final count = completedOn(comps, day); final total = habits.length; final isSelected = DateUtils.isSameDay(day, selected); final inMonth = day.month == month.month; final quality = total == 0 ? 0 : count / total; final color = !inMonth ? Colors.grey : quality >= .7 ? AppColors.green : quality >= .4 ? AppColors.amber : count == 0 ? Colors.grey : AppColors.red; return InkWell(onTap: () => ref.read(selectedDateProvider.notifier).state = DateUtils.dateOnly(day), child: Column(children: [AnimatedContainer(duration: const Duration(milliseconds: 200), width: 46, height: 46, decoration: BoxDecoration(shape: BoxShape.circle, color: color.withOpacity(isSelected ? 1 : .14), border: isSelected ? Border.all(color: AppColors.green, width: 4) : null), child: Center(child: Text('${day.day}', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: isSelected ? Colors.white : color)))), const SizedBox(height: 5), Container(width: 8, height: 8, decoration: BoxDecoration(shape: BoxShape.circle, color: count == 0 ? Colors.transparent : color))])); }), const SizedBox(height: 14), Wrap(spacing: 20, runSpacing: 10, children: const [_Legend(AppColors.green, 'Great (7-9)'), _Legend(AppColors.amber, 'Good (4-6)'), _Legend(AppColors.red, 'Needs work (0-3)'), _Legend(Colors.grey, 'No data')])])),
      const SizedBox(height: 20), SoftCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(DateFormat('EEEE, MMMM d').format(selected), style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w800))), Pill(child: Text('$selectedCount / ${habits.length} completed', style: const TextStyle(color: AppColors.green, fontWeight: FontWeight.w800)))]), const SizedBox(height: 20), Row(children: [MetricMini('✅', '$selectedCount', 'Completed', AppColors.green), const SizedBox(width: 12), MetricMini('⭐', '+${selectedCount * 20}', 'XP Earned', AppColors.amber), const SizedBox(width: 12), const MetricMini('🔥', '12', 'Day Streak', AppColors.red)]), const SizedBox(height: 20), const Text('Completed Habits', style: TextStyle(color: AppColors.green, fontSize: 19, fontWeight: FontWeight.w800)), const SizedBox(height: 10), ...habits.where((h) => comps.any((c) => c.habitId == h.id && DateUtils.isSameDay(c.date, selected))).map((h) => _HistoryRow(h.icon, h.title, h.reminderTimes.first, h.color, true, '+${h.xpReward} XP')), const SizedBox(height: 10), const Text('Missed Habits', style: TextStyle(color: AppColors.red, fontSize: 19, fontWeight: FontWeight.w800)), ...habits.where((h) => !comps.any((c) => c.habitId == h.id && DateUtils.isSameDay(c.date, selected))).map((h) => _HistoryRow(h.icon, h.title, h.subtitle, h.color, false, '🔥 ${h.xpReward ~/ 5 + 3}')), const SizedBox(height: 12), const Row(children: [Text('View all habits', style: TextStyle(color: AppColors.green, fontSize: 18, fontWeight: FontWeight.w800)), Spacer(), Icon(Icons.chevron_right, color: AppColors.green)])])),
    ]);
  }
}

class _Legend extends StatelessWidget { const _Legend(this.color, this.label); final Color color; final String label; @override Widget build(BuildContext context) => Row(mainAxisSize: MainAxisSize.min, children: [Container(width: 10, height: 10, decoration: BoxDecoration(color: color, shape: BoxShape.circle)), const SizedBox(width: 6), Text(label, style: const TextStyle(color: AppColors.muted))]); }
class MetricMini extends StatelessWidget { const MetricMini(this.icon, this.value, this.label, this.color, {super.key}); final String icon, value, label; final Color color; @override Widget build(BuildContext context) => Expanded(child: Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: color.withOpacity(.08), borderRadius: BorderRadius.circular(16)), child: Row(children: [Text(icon, style: const TextStyle(fontSize: 28)), const SizedBox(width: 10), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(value, style: TextStyle(color: color, fontSize: 24, fontWeight: FontWeight.w900)), Text(label, style: const TextStyle(color: AppColors.muted))])]))); }
class _HistoryRow extends StatelessWidget { const _HistoryRow(this.icon, this.title, this.sub, this.color, this.done, this.trailing); final String icon,title,sub,trailing; final Color color; final bool done; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.symmetric(vertical: 8), child: Row(children: [EmojiTile(emoji: icon, color: color, size: 56), const SizedBox(width: 16), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w800)), Text(sub, style: const TextStyle(color: AppColors.muted, fontSize: 16))])), Text(trailing, style: TextStyle(color: done ? AppColors.green : AppColors.orange, fontWeight: FontWeight.w800)), const SizedBox(width: 12), Icon(done ? Icons.check_circle : Icons.circle_outlined, color: done ? AppColors.green : Colors.grey, size: 34)])); }
