import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/widgets/ui.dart';
import '../../../habits/presentation/providers/habit_providers.dart';
import '../../../habits/presentation/widgets/habit_widgets.dart';

class ProgressScreen extends ConsumerWidget { const ProgressScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final habits = ref.watch(habitsControllerProvider); final stats = ref.watch(todayStatsProvider); final vals = [60,80,90,70,85,40,75]; return AppPage(children: [
  Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Progress', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900)), const Text('Track your growth over time', style: TextStyle(fontSize: 22, color: AppColors.muted))])), OutlinedButton.icon(onPressed: (){}, icon: const Icon(Icons.calendar_month), label: const Text('This Week⌄'))]), const SizedBox(height: 24),
  Row(children: [MetricCard(icon: '✅', title: 'Completion Rate', value: '${stats.successRate}%', subtitle: '▲ 12% vs last week', color: AppColors.green), const SizedBox(width: 12), MetricCard(icon: '🔥', title: 'Current Streak', value: '${stats.streak}', subtitle: 'Best: 18 days', color: AppColors.purple)]), const SizedBox(height: 12), Row(children: [MetricCard(icon: '⭐', title: 'Total XP', value: '${stats.xp}', subtitle: '▲ 320 this week', color: AppColors.amber), const SizedBox(width: 12), MetricCard(icon: '🏅', title: 'Habits Completed', value: '42', subtitle: 'This Week', color: AppColors.blue)]), const SizedBox(height: 24),
  SoftCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [const Expanded(child: Text('Completion Over Time', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w900))), const Pill(child: Text('Week', style: TextStyle(color: AppColors.green, fontWeight: FontWeight.w800))), TextButton(onPressed: (){}, child: const Text('Month')), TextButton(onPressed: (){}, child: const Text('Year'))]), SizedBox(height: 250, child: BarChart(BarChartData(maxY: 100, gridData: const FlGridData(show: false), borderData: FlBorderData(show: false), titlesData: FlTitlesData(rightTitles: const AxisTitles(), topTitles: const AxisTitles(), leftTitles: AxisTitles(sideTitles: SideTitles(showTitles: true, reservedSize: 42, getTitlesWidget: (v, _) => Text('${v.toInt()}%'))), bottomTitles: AxisTitles(sideTitles: SideTitles(showTitles: true, getTitlesWidget: (v, _) => Text(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][v.toInt()])))), barGroups: [for (var i=0;i<7;i++) BarChartGroupData(x: i, barRods: [BarChartRodData(toY: vals[i].toDouble(), color: AppColors.green.withOpacity(.65), width: 28, borderRadius: BorderRadius.circular(8))])])))])), const SizedBox(height: 24),
  SoftCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const SectionHeader('Habit Performance', trailing: Row(children: [Text('View All', style: TextStyle(color: AppColors.blue)), Icon(Icons.chevron_right)])), const SizedBox(height: 12), ...habits.map((h) { final pct = switch(h.id){'walk'=>100,'water'=>86,'read'=>71,'workout'=>57,'journal'=>86,_=>64}; return Padding(padding: const EdgeInsets.symmetric(vertical: 10), child: Row(children: [EmojiTile(emoji: h.icon, color: h.color, size: 66), const SizedBox(width: 16), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(h.title, style: const TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), Text('Completed ${(pct/100*7).round()}/7 days', style: const TextStyle(color: AppColors.muted, fontSize: 16)), const SizedBox(height: 8), LinearProgressIndicator(value: pct/100, color: h.color, minHeight: 7, borderRadius: BorderRadius.circular(12))])), const SizedBox(width: 16), Column(children: [Text('$pct%', style: TextStyle(color: h.color, fontSize: 22, fontWeight: FontWeight.w900)), Text('${pct ~/ 10} day streak', style: const TextStyle(color: AppColors.muted))]), const Icon(Icons.chevron_right)])); })])), const SizedBox(height: 24),
  const SoftCard(color: Color(0xFFF0F8ED), child: Row(children: [Text('🪴', style: TextStyle(fontSize: 58)), SizedBox(width: 18), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Insight', style: TextStyle(color: AppColors.green, fontSize: 18, fontWeight: FontWeight.w900)), Text('You’re most consistent on weekdays!\nTry to keep weekends strong too.', style: TextStyle(color: AppColors.muted, fontSize: 17, height: 1.45))])), CircleAvatar(backgroundColor: Color(0xFFE0F3E4), child: Icon(Icons.chevron_right, color: AppColors.green))])),
]); }}
