import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/widgets/ui.dart';
import '../../../habits/presentation/providers/habit_providers.dart';
import '../widgets/profile_widgets.dart';

class ProfileScreen extends ConsumerWidget { const ProfileScreen({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { final stats = ref.watch(todayStatsProvider); return AppPage(children: [
  Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Profile', style: Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight: FontWeight.w900)), const Text('Your journey, your progress 🌿', style: TextStyle(fontSize: 18, color: AppColors.muted))])), const SoftCard(padding: EdgeInsets.all(14), child: Icon(Icons.settings_outlined, size: 28)), const SizedBox(width: 12), Stack(children: [const SoftCard(padding: EdgeInsets.all(14), child: Icon(Icons.notifications_none, size: 28)), Positioned(right: 10, top: 8, child: Container(width: 12, height: 12, decoration: const BoxDecoration(color: AppColors.red, shape: BoxShape.circle)))])]), const SizedBox(height: 26),
  Row(children: [Stack(children: [const SmallAvatar(size: 118), Positioned(right: 4, bottom: 6, child: Container(width: 32, height: 32, decoration: const BoxDecoration(color: AppColors.green, shape: BoxShape.circle), child: const Icon(Icons.edit, color: Colors.white, size: 18)))]) , const SizedBox(width: 28), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Vamsi 👋', style: TextStyle(fontSize: 34, fontWeight: FontWeight.w900)), const Text(mockUserEmail, style: TextStyle(fontSize: 18, color: AppColors.muted)), const SizedBox(height: 18), const Wrap(spacing: 12, runSpacing: 8, children: [Pill(color: Color(0xFFF0ECFF), child: Text('⭐  Level 13', style: TextStyle(color: AppColors.purple, fontWeight: FontWeight.w800))), Pill(child: Text('🔥  12 Day Streak', style: TextStyle(color: AppColors.green, fontWeight: FontWeight.w800)))])]))]), const SizedBox(height: 24),
  const SoftCard(color: Color(0xFFFBF8FF), borderColor: Color(0xFFE4DAFF), child: Row(children: [Text('🛡️', style: TextStyle(fontSize: 62)), SizedBox(width: 20), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Peak Performer', style: TextStyle(color: AppColors.purple, fontSize: 22, fontWeight: FontWeight.w900)), Text('You’re doing amazing!', style: TextStyle(color: AppColors.muted, fontSize: 18)), SizedBox(height: 20), LinearProgressIndicator(value: .71, color: AppColors.purple, minHeight: 8), SizedBox(height: 14), Text('2,847 XP / 4,000 XP to Level 14', style: TextStyle(color: AppColors.muted, fontSize: 17))])), Text('⛰️', style: TextStyle(fontSize: 64))])), const SizedBox(height: 24),
  SoftCard(child: Row(children: [_stat('✅','42','Habits Completed'), _stat('🔥','${stats.streak}','Day Streak'), _stat('⭐','${stats.xp}','Total XP'), _stat('🎯','87%','Success Rate')])), const SizedBox(height: 24),
  const SoftCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text('Badges', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900))), Text('View All', style: TextStyle(color: AppColors.green, fontWeight: FontWeight.w900)), Icon(Icons.chevron_right, color: AppColors.green)]), SizedBox(height: 20), Row(children: [BadgeTile(icon: '🪴', title: 'First Step', sub: 'Complete 1 habit', color: AppColors.green), BadgeTile(icon: '🔥', title: '7 Day Streak', sub: 'Keep it going!', color: AppColors.purple), BadgeTile(icon: '🏆', title: '30 Day Streak', sub: 'Consistency King', color: AppColors.orange), BadgeTile(icon: '🎯', title: 'Habit Master', sub: '10 habits active', color: AppColors.blue), BadgeTile(icon: '👑', title: 'Legend', sub: '100 Day Streak', color: AppColors.amber)]),])), const SizedBox(height: 24),
  const SoftCard(child: Column(children: [SettingRow(icon: '📊', title: 'Statistics & Insights', sub: 'Deep dive into your progress', color: AppColors.green, section: 'statistics'), Divider(), SettingRow(icon: '🎯', title: 'Goals', sub: 'Manage your goals and milestones', color: AppColors.purple, section: 'goals'), Divider(), SettingRow(icon: '⏰', title: 'Reminders', sub: 'Manage your habit reminders', color: AppColors.orange, section: 'reminders'), Divider(), SettingRow(icon: '💗', title: 'Integrations', sub: 'Apple Health, Google Fit & more', color: Colors.pink, section: 'integrations'), Divider(), SettingRow(icon: '☁️', title: 'Backup & Sync', sub: 'Keep your data safe', color: AppColors.blue, section: 'backup')])) , const SizedBox(height: 24),
  const SoftCard(color: Color(0xFFEFF9F0), child: Row(children: [Text('👑', style: TextStyle(fontSize: 46)), SizedBox(width: 20), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Habitura Premium', style: TextStyle(color: AppColors.green, fontSize: 21, fontWeight: FontWeight.w900)), Text('Unlock unlimited habits, advanced insights\nand AI Coach.', style: TextStyle(color: AppColors.muted))])), Pill(color: AppColors.green, child: Text('✨ Upgrade Now', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w900))) ])),
]); }
  static Widget _stat(String icon, String value, String label) => Expanded(child: Column(children: [Text(icon, style: const TextStyle(fontSize: 30)), Text(value, style: const TextStyle(fontSize: 24, fontWeight: FontWeight.w900)), Text(label, textAlign: TextAlign.center, style: const TextStyle(color: AppColors.muted, fontSize: 12))])); }
}
