import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/widgets/ui.dart';
import '../providers/preferences_providers.dart';

class SettingsDetailScreen extends ConsumerWidget { const SettingsDetailScreen({super.key, required this.section}); final String section; @override Widget build(BuildContext context, WidgetRef ref) { final prefs = ref.watch(preferencesProvider); final title = section[0].toUpperCase() + section.substring(1).replaceAll('-', ' '); return Scaffold(body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(24, 28, 24, 42), children: [Row(children: [IconButton.filledTonal(onPressed: () => context.pop(), icon: const Icon(Icons.chevron_left)), const SizedBox(width: 12), Text(title, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900))]), const SizedBox(height: 24), if (section == 'statistics') ..._statistics() else if (section == 'reminders') ...[SoftCard(child: SwitchListTile(value: prefs.remindersEnabled, onChanged: (v) => ref.read(preferencesProvider.notifier).setReminders(v), title: const Text('Habit reminders'), subtitle: const Text('Toggle local reminder UI preference'))), const SizedBox(height: 16), const SoftCard(child: ListTile(leading: Text('⏰', style: TextStyle(fontSize: 30)), title: Text('Default reminder'), subtitle: Text('7:00 AM')))] else if (section == 'backup') ...[const SoftCard(child: ListTile(leading: Text('💾', style: TextStyle(fontSize: 30)), title: Text('Local Hive Storage'), subtitle: Text('Habits, completion history, streaks, and preferences stay on this device.')))] else ...[SoftCard(child: SwitchListTile(value: prefs.darkMode, onChanged: (v) => ref.read(preferencesProvider.notifier).setDark(v), title: const Text('Dark Mode'), subtitle: const Text('Switch Habitura between light and dark mode'))), const SizedBox(height: 16), SoftCard(child: SwitchListTile(value: prefs.weekStartsMonday, onChanged: (v) => ref.read(preferencesProvider.notifier).setWeekStartsMonday(v), title: const Text('Week starts Monday'), subtitle: const Text('Calendar preference stored locally'))), const SizedBox(height: 16), const SoftCard(child: ListTile(leading: Text('🎯', style: TextStyle(fontSize: 30)), title: Text('Current goal'), subtitle: Text('Complete 6 habits per day and keep a 12 day streak.'))), const SizedBox(height: 16), const SoftCard(child: ListTile(leading: Text('🔗', style: TextStyle(fontSize: 30)), title: Text('Integrations'), subtitle: Text('Prepared UI only. External services are intentionally not connected in the MVP.')))] ]))); }
  List<Widget> _statistics() => const [SoftCard(child: ListTile(leading: Text('🏆', style: TextStyle(fontSize: 34)), title: Text('Peak Performer'), subtitle: Text('2,847 XP earned with an 87% success rate.'))), SizedBox(height: 16), SoftCard(child: ListTile(leading: Text('📈', style: TextStyle(fontSize: 34)), title: Text('Best weekday'), subtitle: Text('Wednesday at 90% completion.'))), SizedBox(height: 16), SoftCard(child: ListTile(leading: Text('🔥', style: TextStyle(fontSize: 34)), title: Text('Longest streak'), subtitle: Text('18 days. Keep building consistency.')))]; }
}
